// ============================================================
// ENGINE START — scroll-gsap.js v5.1
// DO NOT MODIFY — copy verbatim between ENGINE START / ENGINE END
// Requires: GSAP + ScrollTrigger loaded before this script
// Config:   window.GSAP_CONFIG defined before this script
// Changelog: engine/CHANGELOG.md
// ============================================================
(function () {
  'use strict';

  // ── GSAP_CONFIG shape ────────────────────────────────────────────────────────
  // window.GSAP_CONFIG = {
  //   videoSrc:      "../assets/video/filename.mp4",
  //   scrollBudget:  "350%",       // total scroll distance pinned to hero
  //   scrubSmooth:   1,            // GSAP scrub smoothing (1 = default, 0 = instant)
  //   fadeRange:     0.18,         // scene fade window (fraction of scroll progress)
  //                                // v5.0 default was 0.09 — raise to 0.18+ for legibility
  //
  //   snapToScenes:  true,         // [v5.1] snap scroll to each scene anchor
  //   snapDelay:     0.3,          // [v5.1] seconds before snap engages after scroll stops
  //                                //        0.1 = snappy, 0.5 = relaxed
  //
  //   videoMap: [                  // anchors: scroll position → video timestamp
  //     { scroll: 0.00, time: 0.0,  label: "intro"  },
  //     { scroll: 0.25, time: 4.2,  label: "reveal" },
  //     { scroll: 0.60, time: 14.8, label: "peak"   },
  //     { scroll: 1.00, time: 30.0, label: "outro"  }
  //   ],
  //                                // TIP: use logs/motion_profile.json (generated by setup.py)
  //                                //      for data-driven videoMap anchors instead of guessing
  //
  //   scenes: [                    // text overlays, positioned from frame log
  //     {
  //       id:      "scene-1",
  //       scroll:  0.08,           // scroll progress where this scene peaks
  //       headline: "HEADLINE",
  //       subhead:  "Subhead text",
  //       pitch:    "Pitch line",
  //       css: { top: "8%", left: "6%" }
  //     }
  //   ]
  // };
  // ────────────────────────────────────────────────────────────────────────────

  const cfg = window.GSAP_CONFIG;
  if (!cfg) { console.error('[scroll-gsap] window.GSAP_CONFIG not found'); return; }

  gsap.registerPlugin(ScrollTrigger);

  const video       = document.getElementById('hero-video');
  const heroSection = document.getElementById('hero-section');
  const progressBar = document.getElementById('hero-progress');
  const scrollHint  = document.getElementById('hero-scroll-hint');

  // ── Chrome autoplay unlock ───────────────────────────────────────────────────
  if (video) {
    video.addEventListener('loadedmetadata', () => {
      video.play().then(() => video.pause()).catch(() => {});
    });
  }

  // ── videoMap interpolation ───────────────────────────────────────────────────
  // Maps a 0–1 scroll progress to the correct video timestamp via the anchors.
  // Between any two anchors it linearly interpolates — giving you non-linear
  // video pacing without codec tricks.
  function mapToVideoTime(progress) {
    const map = cfg.videoMap;
    if (!map || !map.length) return 0;
    if (progress <= map[0].scroll) return map[0].time;
    if (progress >= map[map.length - 1].scroll) return map[map.length - 1].time;
    for (let i = 0; i < map.length - 1; i++) {
      const a = map[i], b = map[i + 1];
      if (progress >= a.scroll && progress <= b.scroll) {
        const t = (progress - a.scroll) / (b.scroll - a.scroll);
        return a.time + t * (b.time - a.time);
      }
    }
    return 0;
  }

  // ── Scene text rendering ─────────────────────────────────────────────────────
  // Fades each scene overlay in and out based on distance from its scroll anchor.
  // fadeRange controls the window — wider = longer crossfades.
  // v5.1: with snapToScenes, the scroll holds exactly at scene.scroll so the
  //       scene reaches full opacity and stays until the user scrolls on.
  function updateScenes(progress) {
    const fadeRange = cfg.fadeRange || 0.18;
    (cfg.scenes || []).forEach(scene => {
      const el = document.querySelector(`[data-scene="${scene.id}"]`);
      if (!el) return;
      const dist    = Math.abs(progress - scene.scroll);
      const opacity = Math.max(0, 1 - dist / fadeRange);
      el.style.opacity = opacity;

      // Stagger children: headline → subhead → pitch
      const children = el.querySelectorAll('[data-stagger]');
      children.forEach(child => {
        const lag     = parseFloat(child.dataset.stagger || 0) * 0.015;
        const delayed = Math.max(0, progress - lag);
        const dist2   = Math.abs(delayed - scene.scroll);
        child.style.opacity = Math.max(0, 1 - dist2 / fadeRange);
      });
    });
  }

  // ── Build snap points from scene anchors [v5.1] ───────────────────────────────
  // Snap positions = [0, ...scene scroll values, 1]
  // Also snaps to start (0) and end (1) of the hero sequence.
  function buildSnapPoints() {
    if (!cfg.snapToScenes) return false;
    const sceneScrolls = (cfg.scenes || []).map(s => s.scroll);
    const points = [0, ...sceneScrolls, 1];
    return {
      snapTo:   points,
      duration: { min: 0.15, max: 0.6 },
      delay:    cfg.snapDelay !== undefined ? cfg.snapDelay : 0.3,
      ease:     'power2.inOut'
    };
  }

  // ── Hero ScrollTrigger — pinned ──────────────────────────────────────────────
  // The hero stays fixed on screen while the user scrolls through scrollBudget.
  // When the budget is spent the pin releases and below-fold content flows in.
  // v5.1: snap option added — when snapToScenes is true, scroll holds at each
  //       scene anchor so the user can read the text before continuing.
  ScrollTrigger.create({
    trigger:  heroSection,
    start:    'top top',
    end:      `+=${cfg.scrollBudget || '300%'}`,
    pin:      true,
    scrub:    cfg.scrubSmooth !== undefined ? cfg.scrubSmooth : 1,
    snap:     buildSnapPoints(),
    onUpdate: (self) => {
      if (video) video.currentTime = mapToVideoTime(self.progress);
      updateScenes(self.progress);

      if (progressBar) progressBa